services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ..:/workspaces:cached
      - ../oc_root:/var/www/html/
      - ../storage:/var/www/storage/
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=opencart
      - MYSQL_USER=opencart_user
      - MYSQL_PASSWORD=opencart_password
    depends_on:
      - db


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db


  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart_user
      MYSQL_PASSWORD: opencart_password
    volumes:
      - db-data:/var/lib/mysql
      
volumes:
  db-data:
  opencart-data: